name: First Workflow
on: 
  push: 
    paths: [.github/workflows/artifacts.yml]
  workflow_dispatch:
jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: npm run, build & test
        run: |
          npm install
          npm run build --if-present
          npm test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules-artifact
          path: |
            dist
            package.json

  build:
    needs: artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: node-modules-artifact
      - name: Display structure of downloaded files
        run: ls -R