name: Environment Variables Workflow
on:
  workflow_dispatch:
jobs:
  show-env:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Output environment variables
        run: echo "My name is ${{ vars.MONGODB_USERNAME }}"