name: Output File Workflow
on: 
  push:
    paths: [.github/workflows/fileoutput.yml]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.publish.outputs.file }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS file name
        id: publish
        run: |
          find dist/assets -type f -name '*.js' -exec bash -c 'echo "file=$1" >> "$GITHUB_OUTPUT"' _ {} \;
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Display File Name
        run: echo "File Name is ${{ needs.job1.outputs.file }}"