name: Output File Workflow
on: 
  push:
    paths: [.github/workflows/fileoutput.yml]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.publish.outputs.file }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS file name
        id: publish
        run: find dist/assets/**.js -type f -execdir echo 'file={}' >> $GITHUB_OUTPUT ';'
		
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Display File Name
        run: echo "File Name is $ {{ needs.job1.publish.outputs.file }}"