name: Output Workflow
on: 
  push:
    paths: [.github/workflows/outputs.yml]
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs: 
        output1: ${{ steps.output1.outputs.name }}
        output2: ${{ steps.output2.outputs.age }}
    steps:
      - name: Output1
        id: output1
        run: echo "name=Raghav" >> "$GITHUB_OUTPUT"

      - name: Output2
        id: output2
        run: echo "age=29" >> "$GITHUB_OUTPUT"

  retrieval:
    needs: publish
    runs-on: ubuntu-latest
    steps:
        - name: Retrieve Outputs
          run: echo "My name is ${{ needs.publish.outputs.output1 }} and I am ${{ needs.publish.outputs.output2 }} years old."
