name: Output Workflow
on:
  push:
    paths:
        - .github/workflows/output.yml
jobs:
  outputs:
    runs-on: ubuntu-latest
    steps:
      - name: GithHub Repo
        env: 
            GITHUB_REPO: ${{ toJSON(github.repository) }}
        run: echo $GITHUB_REPO
      - name: Github Owner
        if: github.repository_owner != 'kyouma'
        run: echo "Repository Owner = ${{ github.repository_owner }}"
