name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
      - name: Dump steps context
        run: echo "${{ toJson(steps) }}"
      - name: Dump runner context
        run: echo "${{ toJson(runner) }}"
