name: Context testing
on: push

jobs:
  github_context_to_logs:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Event Name
        run: echo "${{ toJson(github.event_name) }}"
      - name: Repo URL
        run: echo "${{ toJson(github.repositoryUrl) }}"
      - name: Repo Owner
        run: echo "${{ toJson(github.repository_owner	) }}"
