name: Variables Workflow
on:
  push:
env: 
  name: "Raghav"
  age: "29"
jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo "Name = ${{ env.name }}"
      - name: Print Place
        run: echo "Place = ${{ env.age }}"
      
      - name: Print
        run: echo "My name is ${{ env.name }} and I am ${{ env.age }} years old."
